name: lint-pr-title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install commitlint
        run: yarn global add @commitlint/cli @commitlint/config-conventional

      - name: Configure commitlint
        run: echo "module.exports = {extends${{':'}} ['@commitlint/config-conventional']}" > commitlint.config.js

      - name: Lint PR title
        run: echo ${{ github.event.pull_request.title }} | commitlint
